---
- name: ensure the local store for the clusters conf and keys is available
  local_action: file path=/root/ceph-iscsi-conf state=directory mode=0755
  run_once: True

- name: (local) crt already there?
  local_action:
    module: shell ls -1 /root/ceph-iscsi-conf
  run_once: True
  register: conf_files

- name: (local) create ssl crt/key files
  local_action:
    module: shell cd /root/ceph-iscsi-conf; openssl req -newkey rsa:2048 -nodes -keyout iscsi-gateway.key -x509 -days 365 -out iscsi-gateway.crt -subj "/C=US/ST=./L=./O=RedHat/OU=Linux/CN={{ ansible_hostname }}"
  run_once: True
  when:
    - conf_files.stdout.find('iscsi-gateway.crt') == -1

- name: (local) create pem
  local_action:
    module: shell cd /root/ceph-iscsi-conf;cat iscsi-gateway.crt iscsi-gateway.key > iscsi-gateway.pem
  run_once: True
  register: pem
  when:
    - conf_files.stdout.find('iscsi-gateway.pem') == -1

- name: (local) create public key from pem
  local_action:
    module: shell cd /root/ceph-iscsi-conf; openssl x509 -inform pem -in iscsi-gateway.pem -pubkey -noout > iscsi-gateway-pub.key
  run_once: True
  when:
    - pem.changed

- name: check /etc/ceph current contents
  command: ls -1 /etc/ceph
  register: etc_ceph

- name: copy crt if needed
  copy:
    src: /root/ceph-iscsi-conf/iscsi-gateway.crt
    dest: /etc/ceph/.
  when:
    - "'iscsi-gateway.crt' not in etc_ceph.stdout"

- name: copy priv-key if needed
  copy:
    src: /root/ceph-iscsi-conf/iscsi-gateway.key
    dest: /etc/ceph/.
  when:
    - "'iscsi-gateway.key' not in etc_ceph.stdout"

- name: copy pem if needed
  copy:
    src: /root/ceph-iscsi-conf/iscsi-gateway.pem
    dest: /etc/ceph/.
  when:
    - "'iscsi-gateway.pem' not in etc_ceph.stdout"

- name: copy pub-key if needed
  copy:
    src: /root/ceph-iscsi-conf/iscsi-gateway-pub.key
    dest: /etc/ceph/.
    when:
      - "'iscsi-gateway-pub.key' not in etc_ceph.stdout"

- name: lock ssl file access to root only
  file:
    path: "{{ item }}"
    mode: 0400
  with_items:
    - /etc/ceph/iscsi-gateway.crt
    - /etc/ceph/iscsi-gateway.key
    - /etc/ceph/iscsi-gateway.pem
    - /etc/ceph/iscsi-gateway-pub.key
