---
- name: make sure an installation origin was chosen
  fail:
    msg: "choose an installation origin between repository, distro and local"
  when:
    - ceph_origin != 'repository'
    - ceph_origin != 'distro'
    - ceph_origin != 'local'
  tags:
    - package-install

- name: make sure a repository was chosen
  fail:
    msg: "choose a repository installation source or read https://github.com/ceph/ceph-ansible/wiki"
  when:
    - ceph_origin == 'repository'
    - ceph_repository == 'dummy'
  tags:
    - package-install

- name: fail if local scenario is enabled on debian
  fail:
    msg: "'local' installation scenario not supported on Debian systems"
  when:
    - ansible_os_family == 'Debian'
    - ceph_origin == 'local'

- name: make sure ceph_stable_release is set
  fail:
    msg: "make sure ceph_stable_release is set to a release name (e.g: luminous), http://docs.ceph.com/docs/master/release-notes/"
  when:
    - ceph_stable_release == 'dummy'
    - ceph_repository != 'rhcs'
  tags:
    - package-install

- name: make sure ceph_stable_release is correct
  fail:
    msg: "wrong release name, see http://docs.ceph.com/docs/master/release-notes/"
  when:
    - ceph_stable_release not in ceph_release_num
    - ceph_origin == 'repository'
    - ceph_repository != 'rhcs'
  tags:
    - package-install

- name: verify that a repository type was chosen for ceph rhcs version
  fail:
    msg: "choose between 'cdn' or 'iso' installation, e.g: ceph_repository_type: cdn"
  when:
    - ceph_origin == 'repository'
    - ceph_repository == 'rhcs'
    - ceph_repository_type == 'dummy'
  tags:
    - package-install

- name: verify that ceph_rhcs_cdn_debian_repo url is valid for red hat storage
  fail:
    msg: "ceph_rhcs_cdn_debian_repo url is invalid, please set your customername:customerpasswd"
  when:
    - ceph_origin == 'repository'
    - ceph_repository == 'rhcs'
    - ceph_repository_type == 'cdn'
    - ansible_os_family == 'Debian'
    - ceph_rhcs_cdn_debian_repo == 'https://customername:customerpasswd@rhcs.download.redhat.com'
  tags:
    - package-install

- name: verify that ceph_rhcs_cdn_debian_repo url is valid for red hat storage
  fail:
    msg: "iso installation is not supported by the Ceph Debian rhcs version"
  when:
    - ceph_origin == 'repository'
    - ceph_repository == 'rhcs'
    - ceph_repository_type == 'iso'
    - ansible_os_family == 'Debian'
  tags:
    - package-install

- name: make sure monitor_interface or monitor_address is defined
  fail:
    msg: "you must set monitor_interface or monitor_address"
  when:
    - monitor_interface == 'interface'
    - monitor_address == "0.0.0.0"
    - mon_group_name in group_names
